Dodanie docker-compose
Tomasz-Zdeb/Software-Engineering-Class-Project pull request #72
Opened 2023-04-26 22:25 UTC by wsliwa

Dodałem docker-compose z zaimplementowaną usługą dla API.

W requirements zamieniałem SQLAlchemy na Flask-SQLAlchemy, ponieważ ten drugi był wymagany, a bez pierwszego działało, więc aby nie dublować pakietów zamieniłem. Jeśli jednak będą występować błędy należy przywrócić SQLAlchemy.

Dodałem również psycopg2, a on wymagał pewnych konfiguracji stąd zmiana w Dockerfile'u, gdzie dodane zostało instalowanie pakietów na systemie.

Zapraszam do przetestowania i zgłaszania jakichkolwiek uwag lub błędów.

Aby uruchomić wystarczy można na przykład użyć komendy:
`docker-compose up --build`

2023-04-27 08:38 UTC, Tomasz-Zdeb requested changes
Siema,
- Trzy commity które zasadniczo dotyczą tej samej zmiany należałoby zesquashować w jeden aby nie zaburzać przejrzystości historii zmian
- Czy przetestowałeś zmiany? (jakieś test evidence w komentarzua PRa byłoby mile widziane 🙂 )

2023-04-27 11:08 UTC, jackpie2 commented
Rzeczywiście biblioteki z `requirements.txt` były nieprawidłowe, dodawałem je po implementacji i nie zauważyłem że wymagane są inne, głównie dlatego że miałem zainstalowane wszystkie. 

Co do squashowania commitów, to Github przy mergowaniu ma opcje zesquashowania całego PRa, jeśli byłoby to wygodniejsze niż korzystanie z gitowego CLI.

2023-04-27 22:16 UTC, wsliwa commented
Miałem problem, po wy push'owaniu zmian, chcąc zmienić branch, nie pozwoliło mi, ponieważ dalej widziało jakbym nie commitował zmian. Dopiero użycie konsoli pomogło, dlatego duplikaty.

Czy wystarczy jak użyję `git rebase -i` a nasępnie `git push --force-with-lease`?

Co do testów:

![2023-04-28 00-05-04](https://user-images.githubusercontent.com/94856001/235002600-568dd445-e4ab-491f-9dd4-f2fffb6670a7.gif)

2023-04-28 15:57 UTC, Tomasz-Zdeb commented
Bardzo fajne test evidence, chętnie dowiem się w jaki sposób utworzyłeś taki .gif 👍 

W kwestii rebase to najprościej skorzystać z GUI w VS Code (nie jestem pewien czy to stockowa funkcjonalność czy przychodzi wraz z rozszerzeniem: Git Lens - które jest w sugerowanych extensions w naszym repozytorium), ale będąc na branchu który chce się rebaseować, należy kliknąc prawym przyciskiem na branch na który chce się rebaseować i wybrać z menu konteksowego opcję: _rebase this branch onto XYZ_

Korzystając z CLI: `git rebase --onto <nazwa-brancha-na-ktorego-przeprowadza-sie-rebase> <nazwa-brancha-rebasowanego>`, np. `git rebase --onto master 00-Wykonaj-zadanie-a`

2023-04-29 19:18 UTC, wsliwa commented
Udało mi się połączyć commity.

Co do testów:
- gif'a stworzyłem nagrywając obs'em, a następnie konwertując go online. Z tego co wiem to są programy, które bezpośrednio mogą tworzyć gif'y, ale jeszcze nie testowałem.
- zapomniałem wspomnieć, że testowany był tylko przykładowy endpoint, ponieważ do endpoint note jest wymagana baza danych, a nie miałem czasu jej postawić. Myślę, że warto "popchnąć" dokeryzacje bazy.

2023-04-30 09:09 UTC, Tomasz-Zdeb commented
Dostęp do endpointa ze Swaggerem jest wystarczający w celu potwierdzenia źe aplikacja uruchomiła się poprawnie w kontenerze. Dobra robota :+1: dzięki!

2023-04-30 09:09 UTC, Tomasz-Zdeb approved these changes

2023-04-30 09:22 UTC, merged